#!/usr/bin/env python3
"""Offline checks for canframes.py -- expected bytes are hand-computed from the
Pylontech spec, not generated by the code under test."""
import sys, canframes as cf

FAIL = []
def check(name, got, want):
    ok = got == want
    print(f"  {'ok  ' if ok else 'FAIL'}  {name}")
    if not ok:
        print(f"          got  {got.hex(' ') if isinstance(got, bytes) else got}")
        print(f"          want {want.hex(' ') if isinstance(want, bytes) else want}")
        FAIL.append(name)

# A realistic snapshot: the actual values read off the pack tonight.
SNAP = dict(pack_voltage_v=13.16, current_a=-12.5, soc_percent=48, nominal_ah=105.0,
            cycles=1, protection=0, fet_charge=1, fet_discharge=1, cell_count=4,
            temp1_c=21.5, temp2_c=21.5)

print("\n== frame encoding ==")
f = dict(cf.build_frames(SNAP))

# 0x351: CVL 14.2V=142=0x008E, CCL 50A=500=0x01F4, DCL 80A=800=0x0320, DVL 11V=110=0x006E
check("0x351 limits",   f[0x351], bytes.fromhex("8e00") + bytes.fromhex("f401")
                                 + bytes.fromhex("2003") + bytes.fromhex("6e00"))
# 0x355: SOC 48=0x0030, SOH 100=0x0064
check("0x355 soc/soh",  f[0x355], bytes.fromhex("30006400"))
# 0x356: V 13.16*100=1316=0x0524, I -12.5*10=-125=0xFF83, T 21.5*10=215=0x00D7
check("0x356 v/i/t",    f[0x356], bytes.fromhex("2405") + bytes.fromhex("83ff")
                                 + bytes.fromhex("d700"))
check("0x359 no alarm", f[0x359], bytes([0,0,0,0,1,0x50,0x4E,0]))
check("0x35C both FETs",f[0x35C], bytes([0xC0, 0x00]))
check("0x35E PYLON",    f[0x35E], b"PYLON   ")

print("\n== little-endian / sign handling ==")
neg = dict(SNAP, current_a=-12.5)
pos = dict(SNAP, current_a=+12.5)
check("negative current", dict(cf.build_frames(neg))[0x356][2:4], bytes.fromhex("83ff"))
check("positive current", dict(cf.build_frames(pos))[0x356][2:4], bytes.fromhex("7d00"))

print("\n== alarm mapping ==")
check("cell over-voltage", cf.alarm_bytes(cf.JBD_CELL_OV), (cf.P_OV, 0))
check("cell under-voltage", cf.alarm_bytes(cf.JBD_CELL_UV), (cf.P_UV, 0))
check("charge over-current", cf.alarm_bytes(cf.JBD_CHG_OC), (0, cf.P_CHG_OC))
check("discharge over-current", cf.alarm_bytes(cf.JBD_DSG_OC), (cf.P_DSG_OC, 0))
check("short circuit -> dsg oc", cf.alarm_bytes(cf.JBD_SHORT), (cf.P_DSG_OC, 0))
check("IC error -> system err", cf.alarm_bytes(cf.JBD_IC_ERROR), (0, cf.P_SYS_ERR))
check("over-temp (chg)", cf.alarm_bytes(cf.JBD_CHG_OT), (cf.P_OT, 0))
check("under-temp (dsg)", cf.alarm_bytes(cf.JBD_DSG_UT), (cf.P_UT, 0))
check("combined", cf.alarm_bytes(cf.JBD_CELL_OV | cf.JBD_CHG_OC),
                  (cf.P_OV, cf.P_CHG_OC))
check("no alarm", cf.alarm_bytes(0), (0, 0))

print("\n== FET states reflected in 0x35C ==")
check("charge FET open",    dict(cf.build_frames(dict(SNAP, fet_charge=0)))[0x35C], bytes([0x40,0]))
check("discharge FET open", dict(cf.build_frames(dict(SNAP, fet_discharge=0)))[0x35C], bytes([0x80,0]))
check("both FETs open",     dict(cf.build_frames(dict(SNAP, fet_charge=0, fet_discharge=0)))[0x35C], bytes([0x00,0]))

print("\n== refuses to invent data ==")
check("empty snapshot -> no frames", cf.build_frames({}), [])
check("missing voltage -> no frames", cf.build_frames(dict(SNAP, pack_voltage_v=None) | {} ) if False else
      cf.build_frames({k: v for k, v in SNAP.items() if k != "pack_voltage_v"}), [])
check("missing soc -> no frames",
      cf.build_frames({k: v for k, v in SNAP.items() if k != "soc_percent"}), [])

print("\n== clamping (a BLE glitch must not become a wild frame) ==")
cl = []
wild = dict(SNAP, current_a=99999.0)
fr = dict(cf.build_frames(wild, clamps=cl))
check("absurd current pinned to int16 max", fr[0x356][2:4], bytes.fromhex("ff7f"))
check("clamp was recorded", [n for n, _ in cl], ["current"])

print("\n== frame lengths (CAN max 8) ==")
for cid, data in cf.build_frames(SNAP):
    ok = 0 < len(data) <= 8
    print(f"  {'ok  ' if ok else 'FAIL'}  0x{cid:03X} len={len(data)}  {data.hex(' ')}")
    if not ok: FAIL.append(f"len 0x{cid:03X}")

print()
if FAIL:
    print(f"FAILED: {len(FAIL)} -> {FAIL}"); sys.exit(1)
print("all checks passed")
